preload = /home/naokotani/Pictures/wallpapers/arch/geology.png
preload = /home/naokotani/Pictures/wallpapers/arch/waves.png
wallpaper = eDP-1,/home/naokotani/Pictures/wallpapers/arch/geology.png
wallpaper = DP-1,/home/naokotani/Pictures/wallpapers/arch/waves.png
splash = false
