preload = /home/naokotani/Pictures/wallpapers/norse/hel.png
preload = /home/naokotani/Pictures/wallpapers/norse/valk.png
wallpaper = eDP-1,/home/naokotani/Pictures/wallpapers/norse/hel.png
wallpaper = DP-1,/home/naokotani/Pictures/wallpapers/norse/valk.png
splash = false
