[theme]
primary = "light white"
secondary = "light white"
title = "light white"
playing = "#070019"
playing_selected = "light white"
playing_bg = "#6f80ff"
highlight = "#2270be"
highlight_bg = "#301a4f"
error = "light white"
error_bg = "#cd2f30"
statusbar = "#dedeff"
statusbar_progress = "#b52c2c"
statusbar_bg = "#352487"
cmdline = "light white"
cmdline_bg = "black"
search_match = "#d369af"

# Use "Shift+q" to quit instead of the default "q"
[keybindings]
"Shift+q" = "quit"
"q" = "noop"
