vim.g.loaded_netrwPlugin = 1

require "nao.options"
require "nao.keymaps"
require "nao.plugins"
require "nao.colorscheme"
require "nao.cmp"
require "nao.lsp"
require "nao.telescope"
require "nao.treesitter"
require "nao.autopairs"
require "nao.dired"
require "nao.lualine"
require "nao.buffline"
require "nao.whichkey"
require "nao.gitsigns"
require "nao.dashboard"
require "nao.colorize"
require "nao.conform"
require "nao.project"
require "nao.comments"
require "nao.neogit"
